version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: saas_platform
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
