# Generated by Django 5.2 on 2025-06-28 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="externalapicall",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integrationhealth",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_checks",
                to="integrations.integrationprovider",
            ),
        ),
        migrations.AddField(
            model_name="externalapicall",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_calls",
                to="integrations.integrationprovider",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="integrations.integrationprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="externalapicall",
            index=models.Index(
                fields=["provider", "status"], name="external_ap_provide_abc944_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalapicall",
            index=models.Index(
                fields=["started_at"], name="external_ap_started_6aefb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalapicall",
            index=models.Index(
                fields=["correlation_id"], name="external_ap_correla_aacbfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "status"], name="webhook_eve_provide_0e750a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["event_type", "received_at"],
                name="webhook_eve_event_t_dab77c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["next_retry_at"], name="webhook_eve_next_re_81b31f_idx"
            ),
        ),
    ]
