# Generated by Django 5.2 on 2025-06-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
